ALTER TABLE automation_rules DROP CONSTRAINT automation_rules_trigger_check;
ALTER TABLE automation_rules ADD CONSTRAINT automation_rules_trigger_check CHECK (trigger IN (
    'INCIDENT_CREATED', 'INCIDENT_RESOLVED', 'ALERT_TRIGGERED', 'ALERT_ESCALATED',
    'PROJECT_CRITICAL', 'PROJECT_WARNING', 'CHECK_FAILED', 'CHECK_RECOVERED',
    'MAINTENANCE_STARTED', 'MAINTENANCE_ENDED', 'ROOT_INCIDENT_CREATED'
));
